### ISSUE TITLE
1.21.1 support

### ISSUE THREAD

**Issue by draand28** [ArkFlame/HamsterAPI#20]
Hello,

I noticed that the plugin does not load on 1.21.1 PaperMC, more specifically:

`This server is running Paper version 1.21.1-76-master@e945cfe (2024-09-10T17:56:53Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)`

Please find the attached log below:

`[14:42:39 INFO]: [HamsterAPI] Enabling HamsterAPI v0.2.3
[14:42:39 ERROR]: Error occurred while enabling HamsterAPI v0.2.3 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at HamsterAPI.jar/dev._2lstudios.hamsterapi.HamsterAPI.initialize(HamsterAPI.java:49) ~[HamsterAPI.jar:?]
        at HamsterAPI.jar/dev._2lstudios.hamsterapi.HamsterAPI.onEnable(HamsterAPI.java:83) ~[HamsterAPI.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-76-e945cfe]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[14:42:39 INFO]: [HamsterAPI] Disabling HamsterAPI v0.2.3`

**Comment by linsaftw** [comment]
You are not using latest build
